name: Pipeline DevSecOps
on:
  workflow_dispatch:
jobs:
  bandit:
    name: SAST - Bandit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Instalar Bandit
        run: |
          pip install bandit
      - name: Ejecutar Bandit
        run: |
          mkdir resultados
          bandit -r app-vulnerable -f txt -o resultados/bandit.txt || true
          cat resultados/bandit.txt
      - uses: actions/upload-artifact@v4
        with:
          name: bandit
          path: resultados/bandit.txt
##################################################################################
  safety:
    name: SCA - Safety
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Instalar Safety
        run: |
          pip install safety
      - name: Instalar dependencias del proyecto
        continue-on-error: true
        run: |
          pip install -r app-vulnerable/requirements.txt
      - name: Ejecutar Safety
        continue-on-error: true
        run: |
          safety check -r app-vulnerable/requirements.txt > safety.txt || true
          cat safety.txt
      - uses: actions/upload-artifact@v4
        with:
          name: safety
          path: safety.txt
##################################################################################
  gitleaks:
    name: Secretos - Gitleaks
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
##################################################################################
  trivy:
    name: Docker - Trivy
    runs-on: ubuntu-latest
    needs:
      - safety
    if: always()
    steps:
      - uses: actions/checkout@v4
      - name: Construir imagen
        run: |
          docker build \
            -t vulnerable-app \
            ./DevSecOps/app-vulnerable
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: vulnerable-app
          format: table
          output: trivy.txt
          exit-code: "0"
      - uses: actions/upload-artifact@v4
        with:
          name: trivy
          path: trivy.txt
##################################################################################
    zap:
      name: DAST - OWASP ZAP (Active Scan)
      runs-on: ubuntu-latest
      needs:
        - trivy
      if: always()
      steps:
        - uses: actions/checkout@v4
        - name: Construir Docker
          run: |
            docker build \
              -t vulnerable-app \
              ./app-vulnerable
        - name: Ejecutar contenedor
          run: |
            docker run -d \
              --name vulnerable \
              -p 5000:5000 \
              vulnerable-app
        - name: Esperar Flask
          run: |
            ok=0
            for i in $(seq 1 20); do
              if curl -sf http://localhost:5000 > /dev/null; then
                ok=$((ok+1))
                if [ "$ok" -ge 3 ]; then
                  echo "App estable"
                  exit 0
                fi
              else
                ok=0
              fi
              sleep 1
            done
            echo "La app no se estabilizó a tiempo"
            docker logs vulnerable
            exit 1
        - name: Comprobar aplicación
          run: |
            curl http://localhost:5000
        - name: Ejecutar ZAP Full Scan (Active)
          continue-on-error: true
          uses: zaproxy/action-full-scan@v0.10.0
          with:
            target: "http://localhost:5000"
            cmd_options: "-a"
            allow_issue_writing: false
        - name: Subir reportes de ZAP manualmente
        if: always()
          uses: actions/upload-artifact@v4
          with:
            name: zap-report-active
            path: |
              report_json.json
              report_md.md
              report_html.html
